version: '3.7'
services:
  db:
    image: postgres:15
    container_name: reservation_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.example
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: reservation_redis

  reservation:
    build:
      context: .
    container_name: reservation_app
    env_file:
      - .env.example
    depends_on:
      - db
      - redis
#    command: ["/reservation/docker/app.sh"]
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "7777:8000"

  celery:
    build:
      context: .
    container_name: reservation_celery
#    command: ["/reservation/docker/celery.sh", "celery"]
    command: sh -c "celery --app=app.tasks.celery:celery worker -l INFO"
    env_file:
      - .env.example
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: reservation_flower
#    command: [ "/reservation/docker/celery.sh", "flower" ]
    command: sh -c "celery --app=app.tasks.celery:celery flower"
    env_file:
      - .env.example
    depends_on:
      - redis
    ports:
      - "5555:5555"

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    ports:
        - "3000:3000"

volumes:
  postgres_data:
  grafana_data:
  prometheus_data:
