version: '3.7'
services:
  db:
    image: postgres:15
    container_name: reservation_db
    env_file:
      - .env.example
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: reservation_redis

  reservation:
    build:
      context: .
    container_name: reservation_app
    env_file:
      - .env.example
    depends_on:
      - db
      - redis
#    command: ["/reservation/docker/app.sh"]
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "7777:8000"

  celery:
    build:
      context: .
    container_name: reservation_celery
#    command: ["/reservation/docker/celery.sh", "celery"]
    command: sh -c "celery --app=app.tasks.celery:celery worker -l INFO"
    env_file:
      - .env.example
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: reservation_flower
#    command: [ "/reservation/docker/celery.sh", "flower" ]
    command: sh -c "celery --app=app.tasks.celery:celery flower"
    env_file:
      - .env.example
    depends_on:
      - redis
    ports:
      - "5555:5555"
